Feat/autocomplete component
NoyKerenHLS/Dispatcher-Client pull request #3
Opened 2024-02-15 11:25 UTC by NoyKerenHLS

create autocomplete component

2024-02-18 08:31 UTC, AyalWein requested changes

2024-02-18 08:31 UTC, AyalWein commented on src/components/autocomplete/Autocomplete.tsx
> +  options: string[];
objects

2024-02-18 08:31 UTC, AyalWein commented on src/components/autocomplete/Autocomplete.tsx
> +  const [inputValue, setInputValue] = useState("");
typescript generics

2024-02-18 08:31 UTC, AyalWein commented on src/components/autocomplete/Autocomplete.tsx
> +  const style = searchBarAutocomplete;
use directly

2024-02-19 08:43 UTC, NoyKerenHLS commented on src/components/autocomplete/Autocomplete.tsx
> +  options: string[];
Problematic, will happen later

2024-02-19 13:24 UTC, AyalWein approved these changes

2024-02-19 14:59 UTC, merged